### ISSUE TITLE
A issue with the readme

### ISSUE THREAD

**Issue by WattSkill** [Tennessin/-ARMA-Feburary-#1]
GangMenu dont have the updated one
Vipclub rewritten
Store dont think so
Admin Menu, dont have the updated one
Events dont think so
much more ???

**Comment by elfbars** [comment]
![image](https://github.com/Tennessin/-ARMA-Feburary-/assets/122835363/2ffb711d-c35f-41d2-9d39-a993c6b9aeb2)
when are u adding the 1.3k new commits?
![image](https://github.com/Tennessin/-ARMA-Feburary-/assets/122835363/0052b44f-ad37-4571-a9bc-35bb3f60061d)
